title = "My site"
author = { name = "Vincent Prouillet" }
base_url = "https://replace-this-with-your-url.com"
highlight_code = true
compile_sass = true
generate_feed = true
theme = "sample"

taxonomies = [
    {name = "categories", feed = true},
]

extra_syntaxes = ["syntaxes"]

ignored_content = ["*/ignored.md"]
